### PR TITLE
Feat enable suport to php8

### PR DESCRIPTION
**Pull request by matheusdelima**
Hello @amitavroy

This branch is a result of effort to upgrade this package for support with the PHP 8.0 version.

**This branch includes:**

- PHP Unit Test executable in 7.3, 7.4 and 8.0 PHP version;
- Fix Psalm workflow;
- Fix PHPCS workflow.

**This branch was removed these items:**

- Test in OS Windows;
- Lowest dependency

### CODE REVIEW

**Comment by matheusdelima** [comment]
Hello @amitavroy

This branch is a result of effort to upgrade this package for support with the PHP 8.0 version.

This branch includes:

- PHP Unit Test executable in 7.3, 7.4 and 8.0 PHP version;
- Fix Psalm workflow;
- Fix PHPCS workflow.

This branch was removed these items:

- Test in OS Windows;
-  Lowest dependency

**Comment by matheusdelima** [comment]
Hi @amitavroy,

Has any problem with this pr ?

**Comment by matheusdelima** [comment]
Hi @amitavroy,

Has any problem with this pr ?

**Comment by matheusdelima** [comment]
@amitavroy can you help?

**Review by amitavroy — APPROVED** [review]

**Pull request merged**
